version: "3.9"

volumes:
  db:
  bundle:

services:
  db:
    image: postgres:12.4
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web: &rails
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    env_file: app.env
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '10'

  redis:
    image: redis:5.0.6

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []
