host: <%= ENV['SETTINGS__SMTP__HOST'] %>

smtp:
  address: <%= ENV['SETTINGS__SMTP__ADDRESS'] %>
  domain: <%= ENV['SETTINGS__SMTP__DOMAIN'] %>
  port: <%= ENV['SETTINGS__SMTP__PORT'] %>
  user_name: <%= ENV['SETTINGS__SMTP__USER_NAME'] %>
  password: <%= ENV['SETTINGS__SMTP__PASSWORD'] %>
  authentication: <%= ENV['SETTINGS__SMTP__AUTHENTICATION'] %>
  enable_starttls_auto: <%= ENV['SETTINGS__SMTP__ENABLE_STARTTLS_AUTO'] %>

max_download_visit_record: <%= ENV.fetch('MAX_DOWNLOAD_VISIT_RECORD') { 10000 }.to_i %>
max_download_record: <%= ENV.fetch('MAX_DOWNLOAD_VISIT_RECORD') { 10000 }.to_i %>
user_guide:
  primary_admin: <%= ENV.fetch('USER_GUIDE_VIDEO_LINK_FOR_PRIMARY_ADMIN') { "https://drive.google.com/file/d/1kMWF02tvTIOhvmWDj3KxmY78gPO1K-XZ/view?usp=share_link" } %>
  admin: <%= ENV.fetch('USER_GUIDE_VIDEO_LINK_FOR_ADMIN') { "https://drive.google.com/file/d/1kMWF02tvTIOhvmWDj3KxmY78gPO1K-XZ/view?usp=share_link" } %>
  staff: <%= ENV.fetch('USER_GUIDE_VIDEO_LINK_FOR_STAFF') { "https://drive.google.com/file/d/1F8pSxIFJz4ingsEsXmNE4hMRrjU8P7eQ/view?usp=share_link" } %>
